version: '3.1'

services:
  app:
    container_name: cardenal-server-dev
    image: cardenal-server-dev
    build:
      context: .
      dockerfile: .docker/app.dev.dockerfile
    working_dir: /go
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - .:/go
    env_file:
      - .docker/env/dev.env